# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  name "forge"
  desc "终端启动器：快速切换项目并接管启动 AI 编程助手（Claude Code/Codex 等）"
  homepage "https://github.com/LittleBunVerse/forge"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  on_macos do
    on_intel do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_darwin_amd64.tar.gz"
      sha256 "2a581907fd161e2d44860d97c48e78d14d776be854a0802ee0180f33ba2c7b62"
    end
    on_arm do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_darwin_arm64.tar.gz"
      sha256 "dbc69193518278e54b1205c866bd44c5594779afd3e70366aa2a10319fa2f31c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_linux_amd64.tar.gz"
      sha256 "01ecbd8d7cfb74d5c03de146b6791dc5f126cc8394efeda4acc62e08266888ce"
    end
    on_arm do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_linux_arm64.tar.gz"
      sha256 "d7913cd51de438fbf967253f679d9372cf495c955f7bcacefc7e6edc52b655eb"
    end
  end

  caveats do
    "安装完成后可直接运行："
    "  forge"
  end

  # No zap stanza required
end
