# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  name "forge"
  desc "终端启动器：快速切换项目并接管启动 AI 编程助手（Claude Code/Codex 等）"
  homepage "https://github.com/LittleBunVerse/forge"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  on_macos do
    on_intel do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_darwin_amd64.tar.gz"
      sha256 "91e2759906eac23059857eaec32856d49d94ed1a13204a7dac4163fd1fa8d3f9"
    end
    on_arm do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_darwin_arm64.tar.gz"
      sha256 "acab0c17d450de2c482f445db3710392a91d1822d840cc0d5547700185e375cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_linux_amd64.tar.gz"
      sha256 "c6a3c46395c1b5d2771ec4f0c7583a59cfe1a37e2d3f7b823e5d662987465d5d"
    end
    on_arm do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_linux_arm64.tar.gz"
      sha256 "a0ae85ee9445e9f2a6c6c974ca8f6bd9bed4c40ec0a43ef841636a83fd4441a3"
    end
  end

  caveats do
    "安装完成后可直接运行："
    "  forge"
  end

  # No zap stanza required
end
