# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  name "forge"
  desc "终端启动器：快速切换项目并接管启动 AI 编程助手（Claude Code/Codex 等）"
  homepage "https://github.com/LittleBunVerse/forge"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  on_macos do
    on_intel do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_darwin_amd64.tar.gz"
      sha256 "098dc4156cca2bd0725cf7833dd92d491869656417d4d47bdbc3b2377372bda4"
    end
    on_arm do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_darwin_arm64.tar.gz"
      sha256 "4e14d072069258c63200349fc0c896babd4fb96d035c04cc6ab0988de5c36b95"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_linux_amd64.tar.gz"
      sha256 "daa910baa622477711f2fed61da64f78cdbbd464bdb47cbe738ed3e9eb84ef8a"
    end
    on_arm do
      url "https://github.com/LittleBunVerse/forge/releases/download/v#{version}/forge_#{version}_linux_arm64.tar.gz"
      sha256 "88687a10c754fd28d10aed2b6ab6bf80e401dfbee4ab719e5832d757298d4bc9"
    end
  end

  caveats do
    "安装完成后可直接运行："
    "  forge"
  end

  # No zap stanza required
end
